name: Planning Center Developers
markdown: redcarpet
highlighter: "pygments"
exclude: ["Rakefile","README.md","helpers.rb","tasks"]
timezone: "America/Los_Angeles"
url: http://developers.planningcenteronline.com
