name: Planning Center Developers
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
highlighter: "pygments"
exclude: ["Rakefile","README.md","helpers.rb","tasks"]
timezone: "America/Los_Angeles"
url: http://developers.planningcenteronline.com
collections:
  authors:
    output: true
  teams:
    output: true
